/*
 * cm4_usb_irq_probe -- Phase 7.1 of the CM4 USB arc. Can the CM4 own the USB
 * host port outright: bring up USBPHY2 and the EHCI controller itself, and
 * take USB OTG2's interrupt (IRQ 135, RM Table 4-2) on its own NVIC?
 *
 * CM7 role: boot the CM4 probe image and relay its MU observations to LPUART1.
 * The CM7 configures NO USB register. That is not tidiness -- a CM7 that
 * touched the block would make a CM4 failure invisible, which is the
 * circular-pass shape 3.1 warned about.
 *
 * Tokens over Serial1, streamed by the CM4 over MU channel 0 as
 * (stage marker, observation) pairs:
 *   s1/lpcg     C5B00001 / 1        LPCG115 ungated by the CM4
 *   s2/pllsic   C5B00002 / bit31=LOCK
 *   s3/rstspin  C5B00003 / spin count for USBCMD.RST to clear
 *   s4/usbmode  C5B00004 / CM(3)|SDIS readback
 *   s5/portsc   C5B00005 / PORTSC1 after 100 ms attach window
 *   s6          C5B00006            PCE enabled, NVIC 135 armed
 *   irqcnt      ........            THE ANSWER: >0 = the CM4 took the IRQ
 *   laststs     ........            USBSTS snapshot from the handler
 *   portsc2     ........            PORTSC1 after the observation window
 *   done        D0DE0007
 *
 * Verdict USB_IRQ_CM4=PASS requires: all six stage markers in order, the done
 * marker, PLL lock, host mode, AND irqcnt > 0.
 *
 * QEMU is EXPECTED-FAIL until the model fans IRQ 135 to both NVICs (qemu2
 * wires both USB IRQs to the CM7 NVIC only, fsl-imxrt1170.c:1418). The EVKB
 * is the oracle, and its assertion is physical plug/unplug on J47 moving
 * irqcnt AND PORTSC.CCS together -- a register readback of values the CM4
 * itself just wrote would prove nothing.
 */
#include "Arduino.h"
#include "HardwareSerial.h"
#include "Multicore.h"
#include "MessagingUnit.h"
#include "cm4_usb_probe.h"   /* generated by teensy_add_cm4_image(cm4_usb_probe ...) */

/* Wall-clock, not an iteration count. The SAI probe's spin-count timeout was
 * fine for its ~10 ms window; this probe's observation window is 8 SECONDS,
 * and a spin count large enough for that is both unreadable and
 * compiler-sensitive. 20 s comfortably covers the window plus the PHY waits;
 * anything longer than that is a genuine hang, which the caller reports as a
 * missing token rather than blocking the gate forever. */
static bool wait_recv(uint8_t ch, uint32_t *out) {
    uint32_t start = millis();
    while ((uint32_t)(millis() - start) < 20000u) {
        if (MU.tryReceive(ch, out)) return true;
    }
    return false;
}

static void phex(const char *k, uint32_t v) {
    Serial1.print(k);
    Serial1.print('=');
    for (int s = 28; s >= 0; s -= 4) Serial1.print("0123456789ABCDEF"[(v >> s) & 0xF]);
    Serial1.println();
}

void setup() {
    Serial1.begin(115200);
    Serial1.println("CM4USBIRQ-GATE v1");

    MU.begin();
    Multicore.begin(cm4_usb_probe, sizeof(cm4_usb_probe));

    uint32_t s1 = 0, lpcg = 0, s2 = 0, pllsic = 0, s3 = 0, rstspin = 0;
    uint32_t s4 = 0, usbmode = 0, s5 = 0, portsc = 0, s6 = 0;
    uint32_t irqcnt = 0, laststs = 0, portsc2 = 0, done = 0;

    bool ok = wait_recv(0, &s1)      && wait_recv(0, &lpcg)
           && wait_recv(0, &s2)      && wait_recv(0, &pllsic)
           && wait_recv(0, &s3)      && wait_recv(0, &rstspin)
           && wait_recv(0, &s4)      && wait_recv(0, &usbmode)
           && wait_recv(0, &s5)      && wait_recv(0, &portsc)
           && wait_recv(0, &s6)
           && wait_recv(0, &irqcnt)  && wait_recv(0, &laststs)
           && wait_recv(0, &portsc2) && wait_recv(0, &done);

    phex("s1",      s1);      phex("lpcg",    lpcg);
    phex("s2",      s2);      phex("pllsic",  pllsic);
    phex("s3",      s3);      phex("rstspin", rstspin);
    phex("s4",      s4);      phex("usbmode", usbmode);
    phex("s5",      s5);      phex("portsc",  portsc);
    phex("s6",      s6);
    phex("irqcnt",  irqcnt);  phex("laststs", laststs);
    phex("portsc2", portsc2); phex("done",    done);

    /* Decoded, so a human reading the transcript does not have to remember
     * bit positions -- and so a wrong decode is visible rather than latent. */
    Serial1.print("decode: plllock=");  Serial1.print((pllsic >> 31) & 1u);
    Serial1.print(" hostmode=");        Serial1.print(usbmode & 3u);
    Serial1.print(" sdis=");            Serial1.print((usbmode >> 4) & 1u);
    Serial1.print(" ccs=");             Serial1.print(portsc & 1u);
    Serial1.print(" ccs2=");            Serial1.print(portsc2 & 1u);
    Serial1.println();

    bool stages = (s1 == 0xC5B00001u) && (s2 == 0xC5B00002u) && (s3 == 0xC5B00003u)
               && (s4 == 0xC5B00004u) && (s5 == 0xC5B00005u) && (s6 == 0xC5B00006u)
               && (done == 0xD0DE0007u);
    bool phy   = ((pllsic >> 31) & 1u) != 0u;
    bool host  = (usbmode & 3u) == 3u;

    Serial1.println(stages ? "STAGES=PASS" : "STAGES=FAIL");
    Serial1.println(phy    ? "PHY_PLL_CM4=PASS" : "PHY_PLL_CM4=FAIL");
    Serial1.println(host   ? "HOSTMODE_CM4=PASS" : "HOSTMODE_CM4=FAIL");
    Serial1.println((ok && stages && phy && host && irqcnt > 0u)
                    ? "USB_IRQ_CM4=PASS" : "USB_IRQ_CM4=FAIL");
    Serial1.println("CM4USBIRQ-DONE");
}

void loop() {}
