/*
 * cm4_wire_int_master_test — Phase 4.1: the CM4 self-configures LPI2C5 and
 * runs an INTERRUPT-DRIVEN master (its own LPI2C5 ISR on the CM4 NVIC — the
 * first non-MU peripheral IRQ routed to the CM4, via the qemu2 split-IRQ).
 * The CM7 only boots the CM4 image and reports its MU tokens on LPUART1.
 *
 * Tokens (MU ch0, fixed order):
 *   irqcnt = >0         CM4 serviced the LPI2C5 IRQ (isolated routing proof)
 *   mcr    = 00000001   LPI2C MCR.MEN — master enabled
 *   lpcg   = ........    CCM_LPCG102 readback (informative)
 *   croot  = ........    CCM_CLOCK_ROOT41 readback (informative)
 *   rdv    = ????????    R15 ID read by the CM4 ISR — WORLD-SPLIT:
 *                        QEMU wm8962-stub = 0x0000; silicon = 0x6243
 *   done   = 00000001   CM4 sequence completed
 * WIRE_INT_MASTER_CM4=PASS requires irqcnt>0, mcr=1, done=1.
 */
#include "Arduino.h"
#include "core_pins.h"
#include "HardwareSerial.h"
#include "Multicore.h"
#include "MessagingUnit.h"
#include "cm4_wire_int_master.h"   /* generated by teensy_add_cm4_image */

#define WAIT_LONG 3000000u

static void phex(const char *k, uint32_t v)
{
    Serial1.print(k); Serial1.print('=');
    for (int i = 28; i >= 0; i -= 4)
        Serial1.print("0123456789ABCDEF"[(v >> i) & 0xF]);
    Serial1.println();
}
static void ptimeout(const char *k) { Serial1.print(k); Serial1.println("=TIMEOUT"); }

static bool wait_recv(uint8_t ch, uint32_t *out)
{
    for (uint32_t n = WAIT_LONG; n; n--)
        if (MU.tryReceive(ch, out)) return true;
    return false;
}

void setup()
{
    Serial1.begin(115200);
    Serial1.println("CM4WIREINT-GATE v1");

    MU.begin();
    Multicore.begin(cm4_wire_int_master, sizeof(cm4_wire_int_master));

    static const char *labels[6] = { "irqcnt", "mcr", "lpcg", "croot", "rdv", "done" };
    uint32_t v[6];
    bool ok = true;
    for (int i = 0; i < 6; i++) {
        if (wait_recv(0, &v[i])) phex(labels[i], v[i]);
        else { ptimeout(labels[i]); v[i] = 0xFFFFFFFFu; ok = false; }
    }

    /* rdv (v[4]) is world-dependent -> NOT folded into PASS. */
    bool pass = ok
        && v[0] != 0x0u          /* irqcnt: CM4 took the LPI2C5 IRQ */
        && v[1] == 0x1u          /* mcr.MEN */
        && v[5] == 0x1u;         /* done */
    Serial1.println(pass ? "WIRE_INT_MASTER_CM4=PASS" : "WIRE_INT_MASTER_CM4=FAIL");
    Serial1.println("CM4WIREINT-DONE");
}

void loop() {}
