#!/bin/sh
# Generate ap_creds.h for the ESP8266 bench AP from an RT1176 build's own
# wifi_creds.h -- same contract and same reasoning as the C6 version
# (tools/esp32c6-benchap/make-creds.sh, which carries the full rationale):
# the AP must come up with EXACTLY the credentials the board is already
# compiled against, and the secret moves file to file, never through a shell
# history or a terminal.
#
# Usage:  tools/esp8266-benchap/make-creds.sh [path/to/wifi_creds.h]
set -e
DIR=$(cd "$(dirname "$0")" && pwd)
EVKB=$(cd "$DIR/../.." && pwd)
SRC=${1:-$EVKB/examples/networking/wifi_server_test/build-hw/wifi_creds.h}

[ -f "$SRC" ] || {
    echo "no wifi_creds.h at $SRC" >&2
    echo "That header is generated at CMake configure time from" >&2
    echo "-DM2RADIO_WIFI_SSID/-DM2RADIO_WIFI_PSK.  If the build directory was" >&2
    echo "wiped, the credentials went with it." >&2
    exit 1; }
grep -q '^#define M2_WIFI_PSK' "$SRC" || {
    echo "$SRC has no M2_WIFI_PSK -- was the build configured without credentials?" >&2
    exit 1; }

OUT=$DIR/ap_creds.h
if ! git -C "$EVKB" check-ignore -q "$OUT" 2>/dev/null; then
    echo "$OUT is NOT gitignored -- refusing to write a credential there." >&2
    echo "Add it to .gitignore first." >&2
    exit 1
fi

{
    echo "// Generated by make-creds.sh from the RT1176 build's wifi_creds.h."
    echo "// NEVER committed -- see .gitignore.  Regenerate rather than edit."
    echo "#pragma once"
    sed -n 's/^#define M2_WIFI_SSID/#define AP_SSID/p' "$SRC"
    sed -n 's/^#define M2_WIFI_PSK/#define AP_PSK/p'   "$SRC"
} > "$OUT"

# Report the SSID (public, it is broadcast) and the PSK's LENGTH only.
SSID=$(sed -n 's/^#define AP_SSID[[:space:]][[:space:]]*"\(.*\)"/\1/p' "$OUT")
PSKLEN=$(sed -n 's/^#define AP_PSK[[:space:]][[:space:]]*"\(.*\)"/\1/p' "$OUT" | tr -d '\n' | wc -c | tr -d ' ')
echo "wrote $OUT: ssid=$SSID psk=<$PSKLEN chars>"
[ "$PSKLEN" -ge 8 ] || {
    echo "WARNING: a WPA2 PSK must be at least 8 characters -- softAP() will" >&2
    echo "         refuse this and come up OPEN, which the board will not join." >&2
    exit 1; }
