#!/usr/bin/env python3
"""Convert a raw binary into a C header: static const uint32_t <name>[] = {...}.

Usage: bin2header.py <in.bin> <array_name> > out.h
Little-endian 32-bit words; the binary is zero-padded up to a word boundary.
"""
import sys

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: bin2header.py <in.bin> <array_name>")
    path, name = sys.argv[1], sys.argv[2]
    with open(path, "rb") as f:
        data = f.read()
    if len(data) % 4:
        data += b"\x00" * (4 - len(data) % 4)
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    out = []
    out.append("/* AUTO-GENERATED by cm4/bin2header.py from the compiled CM4 image.")
    out.append(" * Do not edit; rebuild the CM4 sources in cm4/ instead. */")
    out.append("#ifndef cm4_image_h")
    out.append("#define cm4_image_h")
    out.append("#include <stdint.h>")
    out.append("static const uint32_t %s[] = {" % name)
    for i in range(0, len(words), 4):
        row = ", ".join("0x%08X" % w for w in words[i:i + 4])
        out.append("    %s," % row)
    out.append("};")
    out.append("#endif")
    sys.stdout.write("\n".join(out) + "\n")

if __name__ == "__main__":
    main()
