#!/bin/sh
# Generate ap_creds.h for the C6 bench AP from the RT1176 build's own
# wifi_creds.h, so the AP comes up with EXACTLY the SSID and PSK the board is
# already compiled against.
#
# TWO REASONS IT WORKS THIS WAY RATHER THAN TAKING ARGUMENTS:
#
#  1. Swapping the AP must change ONE thing.  If the C6 came up on a different
#     SSID, the RT1176 image would need rebuilding with new credentials and
#     the before/after would differ in two respects -- which is how W11
#     concluded power save was killing RX (its arms differed in boot
#     freshness too) and how W12 spent a morning on "repeated connections".
#
#  2. The secret never has to be typed, pasted, quoted into a shell history,
#     or printed.  It moves file to file.  This repo already leaked live Wi-Fi
#     passwords into pushed history once (W6, redacted at HEAD only), so the
#     handling rule here is the same as the RT1176 side's: scratchpad -> build
#     cache -> generated gitignored header, and nowhere else.  ap_creds.h is
#     in .gitignore before it is ever created.
#
# Usage:  tools/esp32c6-benchap/make-creds.sh [path/to/wifi_creds.h]
set -e
DIR=$(cd "$(dirname "$0")" && pwd)
EVKB=$(cd "$DIR/../.." && pwd)
SRC=${1:-$EVKB/examples/networking/m2_throughput_test/build/wifi_creds.h}

[ -f "$SRC" ] || {
    echo "no wifi_creds.h at $SRC" >&2
    echo "That header is generated at CMake configure time from" >&2
    echo "-DM2RADIO_WIFI_SSID/-DM2RADIO_WIFI_PSK.  If the build directory was" >&2
    echo "wiped, the credentials went with it -- and note what that looks like" >&2
    echo "downstream: the Wi-Fi path compiles out and the board presents" >&2
    echo "exactly like a dead card." >&2
    exit 1; }
grep -q '^#define M2_WIFI_PSK' "$SRC" || {
    echo "$SRC has no M2_WIFI_PSK -- was the build configured without credentials?" >&2
    exit 1; }

OUT=$DIR/ap_creds.h
# Belt and braces: refuse to write if the ignore rule is missing, rather than
# creating a file that git would happily offer to commit.
if ! git -C "$EVKB" check-ignore -q "$OUT" 2>/dev/null; then
    echo "$OUT is NOT gitignored -- refusing to write a credential there." >&2
    echo "Add it to .gitignore first." >&2
    exit 1
fi

{
    echo "// Generated by make-creds.sh from the RT1176 build's wifi_creds.h."
    echo "// NEVER committed -- see .gitignore.  Regenerate rather than edit."
    echo "#pragma once"
    sed -n 's/^#define M2_WIFI_SSID/#define AP_SSID/p' "$SRC"
    sed -n 's/^#define M2_WIFI_PSK/#define AP_PSK/p'   "$SRC"
} > "$OUT"

# Report the SSID (public, it is broadcast) and the PSK's LENGTH only.
# [[:space:]][[:space:]]* rather than a single literal space: the RT1176
# header is generated by CMake and pads the name column, so a one-space
# pattern silently matches nothing and reports a zero-length PSK on a file
# that is perfectly good.  It did exactly that on first run.
SSID=$(sed -n 's/^#define AP_SSID[[:space:]][[:space:]]*"\(.*\)"/\1/p' "$OUT")
PSKLEN=$(sed -n 's/^#define AP_PSK[[:space:]][[:space:]]*"\(.*\)"/\1/p' "$OUT" | tr -d '\n' | wc -c | tr -d ' ')
echo "wrote $OUT: ssid=$SSID psk=<$PSKLEN chars>"
[ "$PSKLEN" -ge 8 ] || {
    echo "WARNING: a WPA2 PSK must be at least 8 characters -- softAP() will" >&2
    echo "         refuse this and come up OPEN, which the board will not join." >&2
    exit 1; }
