/*
 * cm4_graph_usb_capstone -- Phase 7.4, the CAPSTONE of the CM4 USB arc: an
 * AudioStream GRAPH running on the Cortex-M4 feeds the isochronous USB audio
 * stream THE SAME CORE drives.  The CM7 boots the image and relays MU words.
 * It configures no USB register and runs no audio code -- a CM7 that touched
 * either would make a CM4 failure invisible (the circular-pass shape 3.1
 * warned about).
 *
 *   AudioSynthWaveformSine -> AudioOutputUSBHost -> USBAudioOut -> the device
 *                          `-> AudioAnalyzePeak
 *
 * 7.3 (cm4_usb_audio_probe) got the CM4 streaming AUDIBLY from the driver's own
 * tone generator: lps=142332, pkts=8109, xerr=0, unders=0 (EVKB 2026-08-07).
 * The tone generator is gone here.  The ONLY producer is the graph.
 *
 * ★★ THE ARCHITECTURAL RISK THIS GATE EXISTS TO MEASURE, and it is the INVERSE
 * of Phase 6's.  Phase 6 finding 2: on the CM4 the SAI I/O ISR must OUTRANK the
 * AudioStream graph or RX overflows.  Here USB service is NOT an interrupt --
 * it is myusb.Task() + audioOut.service() in the main loop -- while the graph
 * runs from software_isr on IRQ_SOFTWARE = 44.  So the graph unconditionally
 * PREEMPTS USB service, and every graph pass is a contiguous stall in the
 * service loop.  Priority cannot fix that; only cost can.  The CM7 budget
 * measurement (usb_audio_duplex_test/transcript_hw_cpu_budget.txt) says the
 * binding constraint is exactly that: 600 us stalls soak clean, 850 us fail.
 *
 * The two numbers that answer it are printed as a `budget:` line below:
 * gcycmax (worst graph pass) converted to microseconds, and lps, directly
 * comparable with 7.3's 142332 measured WITHOUT the graph.
 *
 * ★★ WHAT THE QEMU GATE CAN AND CANNOT SEE.  Isochronous data does not flow
 * against QEMU's emulated usb-audio (measured 2026-08-06,
 * docs/KNOWN-BROKEN-GATES.md; 7.3's passing gate carries pkts=0).  Because the
 * graph's clock IS packet flow -- AudioOutputUSBHost runs the graph from
 * USBAudioOut's per-frame callback -- the graph is not clocked in QEMU either.
 * So the CM4 image proves the graph SEPARATELY, by pending IRQ_SOFTWARE itself
 * until the FIFO reaches the adapter's setpoint (stage 8), which is pure CPU
 * and works in both worlds.  Four tokens stay WORLD-SPLIT -- STREAM_PACKETS,
 * TRANSPORT_CLEAN, GRAPH_CLOCKED, STREAM_FED -- printed here, presence-checked
 * by run_qemu.sh, value-asserted only on silicon.  ★ Do NOT assert any of them
 * in QEMU: that is 7.1's PHY_PLL_CM4 mistake, which has cost this phase twice.
 *
 * Tokens over Serial1, streamed by the CM4 over MU channel 0 as
 * (stage marker, observation) groups:
 *   s1/dwt       A5B00001 / cycle delta over a bounded spin.  ZERO means CYCCNT
 *                is dead: every USBHost_t36 timeout, the audio control watchdog
 *                AND the graph's own cost accounting are all frozen.
 *   s2/usbintr   A5B00002 / USBINTR after USBHost::begin(); UAIE (18) must be
 *                set or no control transfer can complete.
 *   s3/portsc    A5B00003 / PORTSC1 armed and settled, CCS expected 0.  The
 *                gate hotplugs on THIS marker.
 *   s4/...       A5B00004 / bound + vid + pid.  THE ORACLE: the CM4 image
 *                cannot know them except off the wire.
 *   s5/alt,rate  A5B00005 / the negotiated alternate setting, and the rate the
 *                ★ ADAPTER configured.  main_cm4.cpp never calls format() --
 *                AudioOutputUSBHost's constructor does, from the graph's rate.
 *   s6/ctrl      A5B00006 / queue_fails<<16 | timeouts<<8 | state; all zero.
 *   s7/armed     A5B00007 / beginStreaming(): 32 siTDs allocated and linked.
 *   s8/...       A5B00008 / THE GRAPH, proven in both worlds: gblocks passes
 *                filled the FIFO to fifotgt, peak saw non-silent audio, drop=0,
 *                memuse/memmax bounded, and prio shows the measured polarity.
 *   s9/...       A5B00009 / the 4 s streaming window: pkts, xerr, unders,
 *                queued, gpasses, the graph's cycle counters, cpu%, lps.
 *   done         D0DE000A
 *
 * ★ THE CM7 STREAMS. recv_show() prints each word as it arrives; do not tidy it
 * back into a batch of reads followed by a batch of prints.  The gate polls the
 * UART for s3 and hotplugs the moment it appears, so the connect event lands
 * inside the CM4's armed window.  Batch printing emits s3 only after ALL words
 * have arrived -- i.e. after the window has closed -- and the gate would then
 * plug too late and measure a failure that has nothing to do with the stack.
 * Measured 2026-08-06 on 7.1: it looked identical to a real defect.
 */
#include "Arduino.h"
#include "HardwareSerial.h"
#include "Multicore.h"
#include "MessagingUnit.h"
#include "cm4_graph_usb.h"  /* generated by teensy_add_cm4_image(cm4_graph_usb ...) */

/* The rate the BUILD asked for.  CMakeLists passes the same PROBE_RATE_HZ to
 * both images, and the CM4 side turns it into AUDIO_SAMPLE_RATE_EXACT -- which
 * is what AudioOutputUSBHost's constructor then forces onto USBAudioOut.  So
 * comparing the CM4's reported rate against this constant tests a real link in
 * the chain: that the adapter was constructed and did its one job. */
#ifndef PROBE_RATE_HZ
#define PROBE_RATE_HZ 48000u
#endif

/* The CM4's core clock, for turning its cycle counters into microseconds.
 * Matches cm4_shim/Arduino.h's F_CPU_CM4 and qemu2's modelled CM4 clock
 * (fsl-imxrt1170.c:365).  software_isr stores cycles>>4, hence the x16. */
#define CM4_MHZ 400u

/* Wall-clock, not an iteration count.  The CM4's longest silence is its 10 s
 * claim window (it exits early once the format is negotiated), and its second
 * longest is the 4 s streaming window; 30 s outlasts either with room for PHY
 * bring-up and for the emulator running slower than wall-clock.  Anything past
 * that is a genuine hang, reported as the missing token rather than by blocking
 * the gate forever. */
static bool wait_recv(uint8_t ch, uint32_t *out) {
    uint32_t start = millis();
    while ((uint32_t)(millis() - start) < 30000u) {
        if (MU.tryReceive(ch, out)) return true;
    }
    return false;
}

static void phex(const char *k, uint32_t v) {
    Serial1.print(k);
    Serial1.print('=');
    for (int s = 28; s >= 0; s -= 4) Serial1.print("0123456789ABCDEF"[(v >> s) & 0xF]);
    Serial1.println();
}

/* Receive one word and print it IMMEDIATELY -- see the ★ note in the header. */
static bool recv_show(const char *k, uint32_t *out) {
    if (!wait_recv(0, out)) return false;
    phex(k, *out);
    return true;
}

void setup() {
    Serial1.begin(115200);
    Serial1.println("CM4GRAPHUSB-GATE v1");

    MU.begin();
    Multicore.begin(cm4_graph_usb, sizeof(cm4_graph_usb));

    uint32_t s1 = 0, dwt = 0, s2 = 0, usbintr = 0, s3 = 0, portsc = 0;
    uint32_t s4 = 0, bound = 0, vid = 0, pid = 0;
    uint32_t s5 = 0, alt = 0xFFFFFFFFu, rate = 0, s6 = 0, ctrl = 0, s7 = 0, armed = 0;
    uint32_t s8 = 0, gblocks = 0, fifo = 0, fifotgt = 0, peak = 0, drop = 0;
    uint32_t memuse = 0, memmax = 0, prio = 0;
    uint32_t s9 = 0, pkts = 0, xerr = 0, unders = 0, queued = 0, gpasses = 0;
    uint32_t gcyc = 0, gcycmax = 0, cpu = 0, cpumax = 0, drop2 = 0, peak2 = 0;
    uint32_t memuse2 = 0, loops = 0, lps = 0, elapsed = 0, portsc2 = 0, done = 0;

    bool ok = recv_show("s1",      &s1)      && recv_show("dwt",     &dwt)
           && recv_show("s2",      &s2)      && recv_show("usbintr", &usbintr)
           && recv_show("s3",      &s3)      && recv_show("portsc",  &portsc)
           && recv_show("s4",      &s4)      && recv_show("bound",   &bound)
           && recv_show("vid",     &vid)     && recv_show("pid",     &pid)
           && recv_show("s5",      &s5)      && recv_show("alt",     &alt)
           && recv_show("rate",    &rate)
           && recv_show("s6",      &s6)      && recv_show("ctrl",    &ctrl)
           && recv_show("s7",      &s7)      && recv_show("armed",   &armed)
           && recv_show("s8",      &s8)      && recv_show("gblocks", &gblocks)
           && recv_show("fifo",    &fifo)    && recv_show("fifotgt", &fifotgt)
           && recv_show("peak",    &peak)    && recv_show("drop",    &drop)
           && recv_show("memuse",  &memuse)  && recv_show("memmax",  &memmax)
           && recv_show("prio",    &prio)
           && recv_show("s9",      &s9)      && recv_show("pkts",    &pkts)
           && recv_show("xerr",    &xerr)    && recv_show("unders",  &unders)
           && recv_show("queued",  &queued)  && recv_show("gpasses", &gpasses)
           && recv_show("gcyc",    &gcyc)    && recv_show("gcycmax", &gcycmax)
           && recv_show("cpu",     &cpu)     && recv_show("cpumax",  &cpumax)
           && recv_show("drop2",   &drop2)   && recv_show("peak2",   &peak2)
           && recv_show("memuse2", &memuse2) && recv_show("loops",   &loops)
           && recv_show("lps",     &lps)     && recv_show("elapsed", &elapsed)
           && recv_show("portsc2", &portsc2) && recv_show("done",    &done);

    /* Decoded, so a human reading the transcript does not have to remember bit
     * positions -- and so a wrong decode is visible rather than latent.
     * Separate printf calls throughout: Print::printf truncates at
     * PRINTF_BUF_SIZE (128) bytes PER CALL, silently, and this firmware has
     * more fields per line than that budget allows. */
    Serial1.print("decode: uaie=");   Serial1.print((usbintr >> 18) & 1u);
    Serial1.print(" ccs=");           Serial1.print(portsc  & 1u);
    Serial1.print(" ccs2=");          Serial1.print(portsc2 & 1u);
    Serial1.print(" alt=");           Serial1.print((int32_t)alt);
    Serial1.print(" rate=");          Serial1.print(rate);
    Serial1.print(" ctrl_state=");    Serial1.print(ctrl & 0xFFu);
    Serial1.print(" ctrl_timeouts="); Serial1.print((ctrl >> 8) & 0xFFu);
    Serial1.print(" ctrl_qfails=");   Serial1.print((ctrl >> 16) & 0xFFFFu);
    Serial1.println();

    Serial1.print("graph: blocks=");  Serial1.print(gblocks);
    Serial1.print(" fifo=");          Serial1.print(fifo);
    Serial1.print("/");               Serial1.print(fifotgt);
    Serial1.print(" peak=");          Serial1.print(peak);
    Serial1.print(" dropped=");       Serial1.print(drop);
    Serial1.print(" mem=");           Serial1.print(memuse);
    Serial1.print("/");               Serial1.print(memmax);
    Serial1.println();

    Serial1.print("stream: pkts=");   Serial1.print(pkts);
    Serial1.print(" in ");            Serial1.print(elapsed);
    Serial1.print(" ms, loops=");     Serial1.print(loops);
    Serial1.print(" (");              Serial1.print(lps);
    Serial1.print(" loops/s), xerr="); Serial1.print(xerr);
    Serial1.print(" unders=");        Serial1.print(unders);
    Serial1.print(" queued=");        Serial1.print(queued);
    Serial1.println();

    Serial1.print("stream-graph: gpasses="); Serial1.print(gpasses);
    /* PEAK_NONE, not 0. AudioAnalyzePeak's reset state reads FULL SCALE (its
     * min/max start at +32767/-32768 and read() returns max(|min|,|max|)), so an
     * unguarded read of a tap that analysed nothing reports the loudest possible
     * signal. The CM4 sends this sentinel instead; "none" and "silent" are
     * different faults and must not print the same. */
    Serial1.print(" peak2=");
    if (peak2 == 0xFFFFFFFFu) Serial1.print("none"); else Serial1.print(peak2);
    Serial1.print(" dropped=");       Serial1.print(drop2);
    Serial1.print(" mem=");           Serial1.print(memuse2);
    Serial1.print(" cpu=");           Serial1.print(cpu);
    Serial1.print("%/");              Serial1.print(cpumax);
    Serial1.println("% max");

    /* ★★ THE BUDGET LINE -- the answer Phase 7.4 exists to produce.
     *
     * software_isr stores (cycles >> 4), so x16 recovers cycles and /400
     * microseconds on this core.  Compare `worst` against the CM7-measured knee
     * (600 us contiguous stall soaks clean, 850 us fails); compare `gap` and
     * `lps` against 7.3's 142332 loops/s -- the same 4 s window, the same loop
     * body, with the graph ABSENT.
     *
     * `gap` is the MEAN interval between service() calls, in nanoseconds, which
     * is the quantity the stall budget bounds.  A mean is not a maximum: the
     * worst stall is `worst`, and the two together are what say whether the
     * graph fits. */
    Serial1.print("budget: graph_pass_us last=");
    Serial1.print((gcyc * 16u) / CM4_MHZ);
    Serial1.print(" worst=");         Serial1.print((gcycmax * 16u) / CM4_MHZ);
    Serial1.print(" (cycles ");       Serial1.print(gcycmax * 16u);
    Serial1.println(")");
    Serial1.print("budget: service gap_ns=");
    Serial1.print(lps ? (1000000000u / lps) : 0u);
    Serial1.print(" vs 7.3 lps=142332 (no graph, EVKB); this run lps=");
    Serial1.print(lps);
    Serial1.println();
    /* ★★ THE CAVEAT THAT MUST TRAVEL WITH THOSE TWO LINES, because they are the
     * numbers the whole phase is about and QEMU prints a MEANINGLESS value for
     * them -- one that happens to look alarming.
     *
     * qemu2 derives the CM4's DWT CYCCNT from the virtual clock scaled by the
     * modelled 400 MHz core; it models no M4 pipeline and this gate runs without
     * -icount, so a "cycle" count there is really host emulation time. The first
     * QEMU run of this gate reported worst=776 us, which read as "one graph pass
     * nearly blows the 850 us knee" and is nothing of the sort. The same run's
     * dwt= spin measured 66400 cycles against 7.3's 28800 for identical code.
     *
     * So: compare gcyc/gcycmax/cpu/lps against the CM7 budget ONLY from a
     * silicon transcript. In QEMU they are characterisation, and their one
     * legitimate use is comparing this gate's lps against 7.3's lps IN THE SAME
     * WORLD (67299 there) as a rough instruction-count ratio. */
    Serial1.println("budget: * gcyc/gcycmax/cpu/lps are WORLD-SPLIT characterisation.");
    Serial1.println("budget:   QEMU derives CYCCNT from the virtual clock and models no M4");
    Serial1.println("budget:   pipeline, so ONLY a silicon run may be compared with the");
    Serial1.println("budget:   CM7-measured knee (600us stall clean / 850us fail).");

    Serial1.print("prio: usb135=");   Serial1.print((prio >> 8) & 0xFFu);
    Serial1.print(" graph44=");       Serial1.print(prio & 0xFFu);
    Serial1.println(" (lower = higher priority; usb must outrank the graph)");

    bool stages = (s1 == 0xA5B00001u) && (s2 == 0xA5B00002u) && (s3 == 0xA5B00003u)
               && (s4 == 0xA5B00004u) && (s5 == 0xA5B00005u) && (s6 == 0xA5B00006u)
               && (s7 == 0xA5B00007u) && (s8 == 0xA5B00008u) && (s9 == 0xA5B00009u)
               && (done == 0xD0DE000Au);

    /* Each verdict is its own line, ordered so a red run localises itself. A
     * dead clock, an unarmed mask, a device that never arrived, a device that
     * arrived and was never claimed, a format the device would not accept, a
     * control request it never answered, a ring that would not arm, a graph
     * that did not run, a graph that ran but produced silence, a leaking pool
     * and an inverted priority are ELEVEN different faults.  Collapsing them
     * into one FAIL is how a phase loses a day. */
    bool clock   = dwt != 0u;
    bool intr    = ((usbintr >> 18) & 1u) != 0u;            /* UAIE */
    bool plug    = ((portsc & 1u) == 0u) && ((portsc2 & 1u) == 1u);
    bool claimed = (bound == 1u) && (vid != 0u);
    bool format  = ((int32_t)alt) >= 0;
    bool cseq    = ctrl == 0u;
    bool ready   = armed == 1u;

    /* ★ The rate was set by AudioOutputUSBHost's CONSTRUCTOR from the graph's
     * own AUDIO_SAMPLE_RATE_EXACT; the CM4 main deliberately never calls
     * format().  A mismatch here means the adapter was not constructed, or the
     * build gave the graph and the probe different rates -- the defect that
     * puts a 44100 graph into a 48000 stream and drains the FIFO for good. */
    bool grate   = (rate == PROBE_RATE_HZ);

    /* THE GRAPH RAN, and this is asserted in BOTH worlds because it is pure CPU:
     * passes happened, the adapter's writes were all accepted (drop=0), and the
     * FIFO actually reached the setpoint -- which it can only do if the blocks
     * carried through AudioOutputUSBHost::update() into USBAudioOut's FIFO. */
    bool galive  = (gblocks > 0u) && (drop == 0u) && (fifotgt > 0u) && (fifo >= fifotgt);

    /* ...AND IT CARRIED AUDIO.  Every other number above would look identical if
     * the sine produced silence.  peak is q15 of the largest |sample| the tap
     * saw; the graph asks for amplitude 0.5, so ~16384 is expected.
     *
     * THREE outcomes, not two, and the sentinel is what separates them:
     * 0xFFFFFFFF = the tap analysed no block (a broken graph), 0 = blocks
     * arrived carrying silence (a broken source), anything else = real audio.
     * Without the sentinel the first case would read as FULL SCALE -- see the
     * guard note in main_cm4.cpp. */
    bool gaudio  = (peak != 0xFFFFFFFFu) && (peak > 0u);

    /* Bounded pool, not "drained to zero".  Steady state is exactly ONE live
     * block: update order is construction order and usbSink was constructed
     * before sine, so the sink consumes the block the source produced on the
     * PREVIOUS pass and that block is live across the pass boundary.  memmax=0
     * would mean nothing was ever allocated; a climbing memuse would mean a
     * node stopped releasing. */
    bool gnoleak = (memmax >= 1u) && (memmax <= 4u) && (memuse <= 2u) && (memuse2 <= 2u);

    /* The measured polarity.  Neither number was set by this firmware:
     * AudioStream::update_setup() chose 208 for IRQ_SOFTWARE, USBHost::begin()
     * left IRQ 135 at its reset value.  Lower = higher priority. */
    bool gprio   = (((prio >> 8) & 0xFFu) < (prio & 0xFFu));

    Serial1.println(stages  ? "STAGES=PASS"            : "STAGES=FAIL");
    Serial1.println(clock   ? "DWT_ALIVE=PASS"         : "DWT_ALIVE=FAIL");
    Serial1.println(intr    ? "USBINTR_UAIE=PASS"      : "USBINTR_UAIE=FAIL");
    Serial1.println(plug    ? "PLUG_TRANSITION=PASS"   : "PLUG_TRANSITION=FAIL");
    Serial1.println(claimed ? "DEVICE_CLAIMED=PASS"    : "DEVICE_CLAIMED=FAIL");
    Serial1.println(format  ? "FORMAT_NEGOTIATED=PASS" : "FORMAT_NEGOTIATED=FAIL");
    Serial1.println(cseq    ? "CONTROL_SEQUENCE=PASS"  : "CONTROL_SEQUENCE=FAIL");
    Serial1.println(ready   ? "STREAM_ARMED=PASS"      : "STREAM_ARMED=FAIL");
    Serial1.println(grate   ? "GRAPH_RATE=PASS"        : "GRAPH_RATE=FAIL");
    Serial1.println(galive  ? "GRAPH_ALIVE=PASS"       : "GRAPH_ALIVE=FAIL");
    Serial1.println(gaudio  ? "GRAPH_AUDIO=PASS"       : "GRAPH_AUDIO=FAIL");
    Serial1.println(gnoleak ? "GRAPH_NOLEAK=PASS"      : "GRAPH_NOLEAK=FAIL");
    Serial1.println(gprio   ? "PRIORITY_SPLIT=PASS"    : "PRIORITY_SPLIT=FAIL");

    /* ★★ THE FOUR WORLD-SPLIT TOKENS.  All are PRINTED unconditionally and all
     * are PRESENCE-checked, not value-checked, by the QEMU gate.
     *
     * STREAM_PACKETS  0 in QEMU: isochronous data does not move against the
     *                 emulated usb-audio device.
     * GRAPH_CLOCKED   0 in QEMU as a CONSEQUENCE of that: the graph's clock is
     *                 USBAudioOut's per-frame callback, so no packets means no
     *                 ticks.  Stage 8 is the world-independent graph proof.
     * TRANSPORT_CLEAN trivially PASS in QEMU: a stream that transmitted nothing
     *                 cannot have had a transmission error.
     * STREAM_FED      trivially PASS in QEMU for the same reason: nothing was
     *                 consumed, so the producer cannot have failed to keep up.
     *
     * Asserting the first two in QEMU would make the gate unpassable; asserting
     * the last two would be a check that cannot fail, which this tree treats as
     * worse than no check at all.  On silicon all four mean what they say. */
    Serial1.println(pkts > 0u    ? "STREAM_PACKETS=PASS"  : "STREAM_PACKETS=FAIL");
    Serial1.println(gpasses > 0u ? "GRAPH_CLOCKED=PASS"   : "GRAPH_CLOCKED=FAIL");
    Serial1.println(xerr == 0u   ? "TRANSPORT_CLEAN=PASS" : "TRANSPORT_CLEAN=FAIL");
    Serial1.println(unders == 0u ? "STREAM_FED=PASS"      : "STREAM_FED=FAIL");

    /* The verdict the QEMU gate asserts: the control plane AND the graph.  It
     * stops short of packet flow and of USB-clocked graph passes ON PURPOSE;
     * see the header. */
    bool pass = ok && stages && clock && intr && plug && claimed && format
             && cseq && ready && grate && galive && gaudio && gnoleak && gprio;
    Serial1.println(pass ? "CAPSTONE_CM4=PASS" : "CAPSTONE_CM4=FAIL");
    Serial1.println("CM4GRAPHUSB-DONE");
}

void loop() {}
