// Bench STATION for the RT1176 uAP work (W17).
//
// Joins the OPEN access point hosted by the M.2 IW416 on the MIMXRT1170-EVKB
// and does nothing else.  Association alone is the measurement: the card's own
// STA_LIST is the oracle on the other side, and whether the firmware raises
// EVENT_MICRO_AP_STA_ASSOC (0x2D) when this connects is the open question this
// exists to answer.
//
// ★ NO PASSPHRASE IN THIS FILE, ever.  If client_creds.h exists -- generated by
// make-creds.sh from the AP build's own uap_creds.h, and gitignored before it
// was ever created -- this joins with WPA2.  Without it, it joins an open
// network, which is what every W17 run before the WPA2 work used.
// The secret moves file to file and is never typed, pasted or printed.  This
// repo leaked live Wi-Fi passwords into PUSHED history once; redacting at HEAD
// did not undo that, which is why the rule is mechanical rather than careful.
//
// ★ DHCP, as of the m2_uap_lwip work.  Earlier revisions of this sketch used a
// STATIC address because the AP had no server behind it; now it has one, and
// asking for an address is the whole test -- an address this client did not
// choose, handed out by the AP, is something neither side could have faked.
// Set M2_UAP_CLIENT_STATIC to go back to the static configuration (useful
// against a build of the AP without the DHCP server).
// "Associated" and "addressed" remain SEPARATE claims and are printed as
// separate fields: assoc= says the link is up, ip= says an address was
// obtained, and conflating them is how a half-working AP reads as a working
// one.
//
// Build/flash:
//   arduino-cli compile -b esp8266:esp8266:nodemcuv2 tools/esp8266-uapclient
//   arduino-cli upload  -b esp8266:esp8266:nodemcuv2 -p /dev/cu.usbserial-0001 \
//                       tools/esp8266-uapclient
#include <ESP8266WiFi.h>
#include <WiFiUdp.h>
#if __has_include("client_creds.h")
#include "client_creds.h"       // generated, gitignored -- see make-creds.sh
#endif

static const char *AP_SSID = "RT1176-UAP-TEST";

// Static, because there is no DHCP server on the far side yet.  The addresses
// are private and arbitrary; nothing routes through them.
static IPAddress kIp(192, 168, 44, 50);
static IPAddress kGw(192, 168, 44, 1);
static IPAddress kMask(255, 255, 255, 0);

// ★ LEAVE AND REJOIN ON A CYCLE, rather than testing a leave once by pulling
// power.  A single disconnect proves an event fired once; a cycle shows the AP
// tracking membership BOTH ways, repeatedly, which is what a leave gate would
// have to assert.  It also catches the failure that a one-shot cannot: a count
// that goes 1 -> 0 correctly the first time and then never comes back.
#ifndef CLIENT_CYCLE_MS
#define CLIENT_CYCLE_MS 30000     // stay joined this long...
#endif
#ifndef CLIENT_AWAY_MS
#define CLIENT_AWAY_MS  8000      // ...then stay away this long
#endif
static uint32_t s_phaseAt = 0;
static bool     s_away    = false;
static uint32_t s_cycles  = 0;

static uint32_t s_lastPrint = 0;
static uint32_t s_lastSend  = 0;
static bool     s_wasConnected = false;
static WiFiUDP  s_udp;
static uint32_t s_sent = 0;

// ★ The client must TRANSMIT, not merely associate.  An associated station with
// a static address and nothing to say emits almost nothing, and "no frames
// received" would then be ambiguous between a broken RX path and a silent
// client.  A periodic broadcast removes that ambiguity: every second there is
// something on the air that the AP side must either count or be shown to miss.
// Broadcast rather than unicast so it needs no ARP resolution and no peer.
static const uint16_t kPort = 5001;

void setup() {
    Serial.begin(115200);
    delay(300);
    Serial.println();
    Serial.println("esp8266_uapclient up");
    Serial.print("client_mac=");
    Serial.println(WiFi.macAddress());

    // STATION ONLY.  The ESP8266 ships its own SoftAP on by default and this
    // board has been broadcasting ESP8266TEST; leaving that up during a uAP
    // test would put a second beacon on the air next to the one under test.
    WiFi.softAPdisconnect(true);
    WiFi.mode(WIFI_STA);
    // ★ POWER SAVE OFF, and it is a measurement rather than a tidy-up.  An
    // ESP8266 station sleeps between beacons by default, and an AP is then
    // obliged to BUFFER for it and deliver at DTIM.  Run 13 saw only 11 replies
    // to 26 ARP requests with sleep ON; if that ratio moves with this one line,
    // the AP-side buffering is the explanation and the driver is not at fault.
    // If it does NOT move, the leading candidate is eliminated and the next
    // suspect is lwip rate-limiting or air loss.
    WiFi.setSleepMode(WIFI_NONE_SLEEP);
    WiFi.persistent(false);
    WiFi.setAutoReconnect(true);
#if defined(M2_UAP_CLIENT_STATIC)
    WiFi.config(kIp, kGw, kMask);
    Serial.println("addr_mode=static");
#else
    Serial.println("addr_mode=dhcp");
#endif
    Serial.print("joining ssid="); Serial.print(AP_SSID);
#if defined(CLIENT_PSK)
    Serial.println(" security=wpa2-psk");
    WiFi.begin(AP_SSID, CLIENT_PSK);
#else
    Serial.println(" security=open");
    WiFi.begin(AP_SSID);          // open network: no passphrase argument
#endif
}

void loop() {
#if !defined(CLIENT_NO_CYCLE)
    const uint32_t now = millis();
    if (!s_away && now - s_phaseAt >= CLIENT_CYCLE_MS) {
        s_away = true; s_phaseAt = now; s_cycles++;
        Serial.print("client_leaving cycle="); Serial.println(s_cycles);
        // Disconnect WITHOUT wiping stored config, then stop auto-reconnect so
        // the away phase is actually away -- otherwise the SDK rejoins within
        // a second and the AP sees a blip rather than a leave.
        WiFi.setAutoReconnect(false);
        WiFi.disconnect(false);
    } else if (s_away && now - s_phaseAt >= CLIENT_AWAY_MS) {
        s_away = false; s_phaseAt = now;
        Serial.print("client_rejoining cycle="); Serial.println(s_cycles);
        WiFi.setAutoReconnect(true);
#if defined(CLIENT_PSK)
        WiFi.begin(AP_SSID, CLIENT_PSK);
#else
        WiFi.begin(AP_SSID);
#endif
    }
#endif
    const bool up = (WiFi.status() == WL_CONNECTED);
    if (up != s_wasConnected) {
        s_wasConnected = up;
        Serial.print("client_state=");
        Serial.print(up ? "ASSOCIATED" : "disconnected");
        if (up) {
            Serial.print(" bssid=");   Serial.print(WiFi.BSSIDstr());
            Serial.print(" ch=");      Serial.print(WiFi.channel());
            Serial.print(" rssi=");    Serial.print(WiFi.RSSI());
            Serial.print(" ip=");      Serial.print(WiFi.localIP().toString());
        }
        Serial.println();
    }
    if (up && millis() - s_lastSend >= 1000) {
        s_lastSend = millis();
        IPAddress bcast(192, 168, 44, 255);
        if (s_udp.beginPacket(bcast, kPort)) {
            s_udp.write("RT1176-UAP-CLIENT-HELLO", 23);
            if (s_udp.endPacket()) s_sent++;
        }
    }
    if (millis() - s_lastPrint >= 5000) {
        s_lastPrint = millis();
        // status() and localIP() are separate claims -- see the header note.
        Serial.print("hb status="); Serial.print((int)WiFi.status());
        Serial.print(" assoc=");    Serial.print(up ? 1 : 0);
        Serial.print(" ip=");       Serial.print(WiFi.localIP().toString());
        Serial.print(" sent=");     Serial.println(s_sent);
    }
}
