#!/bin/sh
# Generate client_creds.h for the bench station from the m2_uap_lwip build's own
# uap_creds.h, so the client joins with EXACTLY the passphrase the AP is
# compiled against.
#
# Same reasoning as tools/esp32c6-benchap/make-creds.sh, which this mirrors:
#  1. Swapping a passphrase must change ONE thing.  A client configured
#     independently is a second variable, and a join failure then has two
#     candidate causes instead of none.
#  2. The secret is never typed, pasted, quoted into a shell history, or
#     printed.  It moves file to file.  This repo leaked live Wi-Fi passwords
#     into PUSHED history once; redacting at HEAD did not undo it.
#
# Usage:  tools/esp8266-uapclient/make-creds.sh [path/to/uap_creds.h]
set -e
DIR=$(cd "$(dirname "$0")" && pwd)
EVKB=$(cd "$DIR/../.." && pwd)
SRC=${1:-$EVKB/examples/networking/m2_uap_lwip/build-hw/uap_creds.h}

[ -f "$SRC" ] || {
    echo "no uap_creds.h at $SRC" >&2
    echo "It is generated at CMake configure time from -DM2_UAP_PSK.  If the" >&2
    echo "build directory was wiped the passphrase went with it -- and note how" >&2
    echo "that presents: the AP silently comes up OPEN while this client keeps" >&2
    echo "trying to join with WPA2 and never associates." >&2
    exit 1; }
grep -q '^#define M2_UAP_PSK_STR' "$SRC" || {
    echo "$SRC has no M2_UAP_PSK_STR -- was the AP configured without -DM2_UAP_PSK?" >&2
    exit 1; }

OUT=$DIR/client_creds.h
if ! git -C "$EVKB" check-ignore -q "$OUT" 2>/dev/null; then
    echo "$OUT is NOT gitignored -- refusing to write a credential there." >&2
    exit 1
fi

{
    echo "// Generated by make-creds.sh from the AP build's uap_creds.h."
    echo "// NEVER committed -- see .gitignore.  Regenerate rather than edit."
    echo "#pragma once"
    sed -n 's/^#define M2_UAP_PSK_STR/#define CLIENT_PSK/p' "$SRC"
} > "$OUT"

PSKLEN=$(sed -n 's/^#define CLIENT_PSK[[:space:]][[:space:]]*"\(.*\)"/\1/p' "$OUT" | tr -d '\n' | wc -c | tr -d ' ')
echo "wrote $OUT: psk=<$PSKLEN chars>"
[ "$PSKLEN" -ge 8 ] || { echo "WARNING: WPA2 needs >= 8 characters" >&2; exit 1; }
